Repository googleinterns/major-tom, pull requests merged in 2020-08, with the labels that each got.

#41 Remove exception check for languages not supported
  services/search/search_engine.py
Labels: bug

#43 feature (error handling) Add error handling and logging on the frontend.
  app/package.json
  app/src/views/search-engine/index.js
  app/yarn.lock
  server/resolvers/article/queries.js
  server/tests/queries.test.js
Labels: enhancement

#48 Add x tag for part of speech keywords
  services/keywords/constants.py
Labels: bug

#45 feature (loading) Add loading functionality when searching.
  app/src/views/search-engine/components/search-bar/index.js
  app/src/views/search-engine/index.js
Labels: enhancement

#55 Fixing Key value that causes errors
  services/search/search_engine.py
Labels: bug

#30 Add concurrent api calling for synonyms
  services/search/requirements.txt
  services/search/synonym_extractor.py
  services/search/testing/test_constants.py
  services/search/testing/test_search_engine.py
  services/search/utils.py
Labels: enhancement

#67 quick fix: change utils to synonym_extractor
  services/search/requirements.txt
  services/search/search_engine.py
  services/search/testing/test_constants.py
  services/search/testing/test_search_engine.py
Labels: bug

#56 feature (cache) Add caching service to database requests.
  server/Dockerfile
  server/config/index.js
  server/index.js
  server/package.json
  server/resolvers/article/queries.js
  server/tests/mocks/index.js
  server/tests/queries.test.js
  server/utils/in-memory-cache.js
  server/yarn.lock
Labels: enhancement

#75 refactor (match api spec) Update left non-existent attribute.
  services/parser-database/connector.py
Labels: bug

#70 Changed Parser to use Regex for article identification
  services/parser-database/parser.py
  services/parser-database/tests/test_articles.py
  services/parser-database/tests/test_endpoints.py
Labels: enhancement

#78 Add test for save keywords in memory
  services/parser-database/tests/test_connector.py
Labels: bug

#52 Improve search engine with 3 new factors
  services/parser-database/app.py
  services/parser-database/connector.py
  services/parser-database/requirements.txt
  services/parser-database/tests/test_connector.py
Labels: enhancement

#87 bugfix (cache) Add expiration to cached articles to flush them periodically.
  server/index.js
  server/package.json
  server/resolvers/article/queries.js
  server/tests/queries.test.js
  server/utils/in-memory-cache.js
  server/yarn.lock
Labels: bug

#88 enhancement (welcome-message) Add welcome message and fix display styles.
  app/src/views/search-engine/components/search-bar/index.js
  app/src/views/search-engine/components/search-bar/styles.js
  app/src/views/search-engine/index.js
  app/src/views/search-engine/styles.js
Labels: enhancement

#89 bugfix (article card) Set maxHeight on article cards to fix height issue.
  app/src/views/search-engine/components/articles-list/styles.js
Labels: bug

#91 Re raise status codes which are not 200
  services/parser-database/connector.py
  services/parser-database/requirements.txt
  services/parser-database/retriever.py
  services/parser-database/tests/test_connector.py
  services/parser-database/tests/test_retriever.py
  services/search/search_engine.py
  services/search/synonym_extractor.py
  services/search/testing/test_constants.py
  services/search/testing/test_search_engine.py
Labels: bug

#90 Add golden set
  golden-set.md
Labels: documentation
